<a href="https://colab.research.google.com/github/Rakshit-Gupta-77/Machine-Learning-Journey/blob/main/api_to_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import pandas as pd
import requests

In [47]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=ed24ea3e389f7d7c3fa580bbc82bd37a&language=en-US&page=1')

In [50]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [51]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,80.2106,9.183,360
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,85.4444,9.148,1173
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,50.3237,8.866,2193
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,17.2220,8.836,383
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,65.2243,8.801,2163

In [53]:
for i in range(1,429):
    response = requests.get(
    'https://api.themoviedb.org/3/movie/top_rated?api_key=ed24ea3e389f7d7c3fa580bbc82bd37a&language=en-US&page={}'.format(i)
)
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [54]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,80.2106,9.183,360
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,85.4444,9.148,1173
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,50.3237,8.866,2193
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,17.2220,8.836,383
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,65.2243,8.801,2163
...,...,...,...,...,...,...,...
17135,425505,Kin,A young boy finds a powerful otherworldly weap...,2018-08-29,4.9631,6.087,900
17136,1317672,Love Me Love Me,"After her brother's death, June moves to Milan...",2026-02-12,18.7025,6.086,314
17137,36670,Never Say Never Again,James Bond returns as the secret agent 007 to ...,1983-10-07,13.3018,6.100,1685
17138,14248,Igor,A cliché hunchbacked evil scientist's assistan...,2008-09-19,5.4318,6.100,633
17139,13168,Smiley Face,"Jane, a struggling but perpetually stoned actr...",2007-11-16,6.0628,6.086,348

In [55]:
df.shape

(17140, 7)

In [56]:
df.to_csv('movies.csv')

In [57]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,80.2106,9.183,360
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,85.4444,9.148,1173
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,50.3237,8.866,2193
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,17.2220,8.836,383
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,65.2243,8.801,2163
...,...,...,...,...,...,...,...
17135,425505,Kin,A young boy finds a powerful otherworldly weap...,2018-08-29,4.9631,6.087,900
17136,1317672,Love Me Love Me,"After her brother's death, June moves to Milan...",2026-02-12,18.7025,6.086,314
17137,36670,Never Say Never Again,James Bond returns as the secret agent 007 to ...,1983-10-07,13.3018,6.100,1685
17138,14248,Igor,A cliché hunchbacked evil scientist's assistan...,2008-09-19,5.4318,6.100,633
17139,13168,Smiley Face,"Jane, a struggling but perpetually stoned actr...",2007-11-16,6.0628,6.086,348